apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: demo-web-claim
  name: demo-web-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
