apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: demo-web
  name: demo-external-service
  namespace: default
spec:
  ports:
  - nodePort: 32588
    port: 4567
    protocol: TCP
    targetPort: 4567
  selector:
    io.kompose.service: demo-web
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
